# Generated by Django 4.1.6 on 2023-02-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Artista', models.CharField(max_length=50)),
                ('Año', models.PositiveBigIntegerField()),
                ('Genero', models.CharField(max_length=50)),
                ('Disquera', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Genero', models.CharField(max_length=50)),
                ('Pais', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Artista', models.CharField(max_length=50)),
                ('Genro', models.CharField(max_length=50)),
                ('Album', models.CharField(max_length=50)),
            ],
        ),
    ]
